  services:
    backend:
      environment:
        FRAPPE_REDIS_CACHE: "redis://redis-cache:6379"
        FRAPPE_REDIS_QUEUE: "redis://redis-queue:6379"
        REDIS_CACHE: redis-cache:6379
        REDIS_QUEUE: redis-queue:6379
        SOCKETIO_PORT: 9000
      depends_on:
        - redis-cache
        - redis-queue

    websocket:
      environment:
        FRAPPE_REDIS_CACHE: "redis://redis-cache:6379"
        FRAPPE_REDIS_QUEUE: "redis://redis-queue:6379"
        REDIS_CACHE: redis-cache:6379
        REDIS_QUEUE: redis-queue:6379
      depends_on:
        - redis-cache
        - redis-queue

    queue-short:
      environment:
        FRAPPE_REDIS_CACHE: "redis://redis-cache:6379"
        FRAPPE_REDIS_QUEUE: "redis://redis-queue:6379"
        REDIS_CACHE: redis-cache:6379
        REDIS_QUEUE: redis-queue:6379
      depends_on:
        - redis-cache
        - redis-queue

    queue-long:
      environment:
        FRAPPE_REDIS_CACHE: "redis://redis-cache:6379"
        FRAPPE_REDIS_QUEUE: "redis://redis-queue:6379"
        REDIS_CACHE: redis-cache:6379
        REDIS_QUEUE: redis-queue:6379
      depends_on:
        - redis-cache
        - redis-queue

    scheduler:
      environment:
        FRAPPE_REDIS_CACHE: "redis://redis-cache:6379"
        FRAPPE_REDIS_QUEUE: "redis://redis-queue:6379"
        REDIS_CACHE: redis-cache:6379
        REDIS_QUEUE: redis-queue:6379
      depends_on:
        - redis-cache
        - redis-queue

    frontend:
      environment:
        FRAPPE_REDIS_CACHE: "redis://redis-cache:6379"
        FRAPPE_REDIS_QUEUE: "redis://redis-queue:6379"
        REDIS_CACHE: redis-cache:6379
        REDIS_QUEUE: redis-queue:6379

  volumes:
    redis-queue-data: {}
